# Generated by Django 3.1.6 on 2021-03-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicus',
            name='method',
            field=models.ManyToManyField(related_name='methods', to='app.Methods'),
        ),
    ]
