# Generated by Django 2.2.18 on 2021-02-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('idRecords', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nameTherapeft', models.CharField(max_length=60)),
                ('therapyMethods', models.TextField()),
                ('urlsLrgeFoto', models.URLField()),
                ('urlsSmlFoto', models.URLField()),
                ('timeLoadToDB', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
