# Generated by Django 2.2.18 on 2021-02-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLINICUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRecords', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('Methods', models.TextField()),
                ('urlsLrgeFoto', models.URLField()),
                ('urlsSmlFoto', models.URLField()),
                ('timeLoad', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
