# Generated by Django 2.2.18 on 2021-02-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Database',
            new_name='therapyst',
        ),
    ]
