# Generated by Django 2.2.18 on 2021-02-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='methods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='clinicus',
            name='Methods',
        ),
        migrations.AddField(
            model_name='clinicus',
            name='Methods',
            field=models.ManyToManyField(to='app.methods'),
        ),
    ]
