# Generated by Django 2.2.18 on 2021-02-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210225_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methods',
            name='therapy',
            field=models.TextField(unique=True),
        ),
    ]
