# Generated by Django 2.2.18 on 2021-02-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210223_1025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='therapyst',
            new_name='therapysts',
        ),
    ]
