# Generated by Django 2.2.18 on 2021-02-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210223_1040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='therapysts',
            new_name='THERAPEFT',
        ),
    ]
